spring:
  application:
    name: security   # ?????? ??

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/security   # DB? ??
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update   # (create, create-drop, update, validate ? ??)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false